package sandbox

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/fgrehm/crib/internal/plugin"
)

// policy holds the resolved sandbox policy for bwrap.
type policy struct {
	WorkspaceFolder string
	RemoteHome      string
	DenyPaths       []denyRule // from discovery + user config
	AllowWritePaths []string   // extra writable paths from user config
}

// buildPolicy merges discovered plugin artifacts with user config into a
// resolved policy for the bwrap wrapper script.
func buildPolicy(cfg *sandboxConfig, workspaceDir, remoteUser, workspaceFolder string) *policy {
	remoteHome := plugin.InferRemoteHome(remoteUser)

	// Auto-discovered deny rules from other plugins.
	rules := discoverPluginArtifacts(workspaceDir, remoteUser)

	// User-configured deny-read paths.
	for _, p := range cfg.DenyRead {
		rules = append(rules, denyRule{
			Path:     expandHome(p, remoteHome),
			DenyRead: true,
		})
	}

	// User-configured deny-write paths.
	for _, p := range cfg.DenyWrite {
		rules = append(rules, denyRule{
			Path:     expandHome(p, remoteHome),
			DenyRead: false,
		})
	}

	// Extra writable paths.
	allow := make([]string, 0, len(cfg.AllowWrite))
	for _, p := range cfg.AllowWrite {
		allow = append(allow, expandHome(p, remoteHome))
	}

	return &policy{
		WorkspaceFolder: workspaceFolder,
		RemoteHome:      remoteHome,
		DenyPaths:       rules,
		AllowWritePaths: allow,
	}
}

// generateWrapperScript produces the sandbox wrapper script content.
func generateWrapperScript(pol *policy) string {
	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# Generated by crib sandbox plugin. Do not edit.\n")
	fmt.Fprintf(&b, "# Policy: workspaceFolder=%s\n\n", pol.WorkspaceFolder)

	b.WriteString("exec bwrap \\\n")
	b.WriteString("  --ro-bind / / \\\n")
	b.WriteString("  --dev /dev \\\n")
	b.WriteString("  --proc /proc \\\n")

	// Writable workspace folder.
	wsf := plugin.ShellQuote(pol.WorkspaceFolder)
	fmt.Fprintf(&b, "  --bind '%s' '%s' \\\n", wsf, wsf)
	// Writable /tmp.
	b.WriteString("  --bind /tmp /tmp \\\n")

	// Extra writable paths from user config.
	for _, p := range pol.AllowWritePaths {
		ep := plugin.ShellQuote(p)
		fmt.Fprintf(&b, "  --bind '%s' '%s' \\\n", ep, ep)
	}

	// Deny rules.
	// deny-read: --tmpfs masks real contents with an empty tmpfs.
	// deny-write: --ro-bind re-mounts the path read-only, overriding any
	//   writable --bind above (e.g. a denyWrite path under workspaceFolder).
	for _, rule := range pol.DenyPaths {
		ep := plugin.ShellQuote(rule.Path)
		if rule.DenyRead {
			fmt.Fprintf(&b, "  --tmpfs '%s' \\\n", ep)
		} else {
			fmt.Fprintf(&b, "  --ro-bind '%s' '%s' \\\n", ep, ep)
		}
	}

	b.WriteString("  -- \"$@\"\n")

	return b.String()
}

// generateAliasScript produces a wrapper script for an agent alias.
func generateAliasScript(alias, realBinaryPath, sandboxPath string) string {
	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# Generated by crib sandbox plugin. Do not edit.\n")
	fmt.Fprintf(&b, "echo '[crib sandbox] Running %s in sandboxed mode'\n", alias)
	fmt.Fprintf(&b, "exec '%s' '%s' \"$@\"\n", plugin.ShellQuote(sandboxPath), plugin.ShellQuote(realBinaryPath))
	return b.String()
}

// expandHome replaces ~/ prefix with the container home directory.
func expandHome(path, remoteHome string) string {
	if strings.HasPrefix(path, "~/") {
		return filepath.Join(remoteHome, path[2:])
	}
	return path
}
