version: 2

project_name: crib

builds:
  - main: .
    binary: crib
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/fgrehm/crib/cmd.Version={{ .Version }}
      - -X github.com/fgrehm/crib/cmd.Commit={{ .ShortCommit }}
      - -X github.com/fgrehm/crib/cmd.Built={{ .Date }}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  use: github-native

release:
  github:
    owner: fgrehm
    name: crib
