name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main, stable]
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/test.yml
